### ISSUE TITLE
不支持自定义函数  类调用?

### ISSUE THREAD

**Issue by lsamu** [shenfe/Velocity#2]
function aa($a,$b){
    return [1,2,3,4]
}

${aa(1,2)}

class test{
    function bb($a,$b){
         return [1,2,3,4]
   }
}

#foreach($row in $test.bb(1,2))
    $row
#end

**Comment by shenfe** [comment]
@lsamu 不支持，因为模板语法是与语言（js/php/java）无关的，否则就不是通用模板了。要实现procedure可以试试用宏，macro。
